version: '3.8'

services:

  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: library-database
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build:
      context: .
      args:
        APP_NAME: app
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge